version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/mydb
      - JWT_SECRET=supersecret
      - JWT_EXPIRATION=8h
      - JWT_REFRESH_SECRET=refreshsecret
      - JWT_REFRESH_EXPIRATION=5d
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project-frontend
    restart: unless-stopped
    ports:
      - '5173:4173'
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: project-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: